# Generated by Django 2.2 on 2019-07-20 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uquestion',
            name='repeated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='uquestion',
            name='attempt_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='attemp_questions'),
        ),
        migrations.AlterField(
            model_name='uquestion',
            name='correct_answer',
            field=models.IntegerField(blank=True, null=True, verbose_name='correct_answer'),
        ),
        migrations.AlterField(
            model_name='uquestion',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='quiz.Question', verbose_name='Questio'),
        ),
        migrations.AlterField(
            model_name='uquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to='quiz.Quiz', verbose_name='Quiz1'),
        ),
        migrations.AlterField(
            model_name='uquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
