# Generated by Django 2.2.3 on 2019-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedquiz',
            name='tempory_questions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='tempory_questions'),
        ),
    ]
