# Generated by Django 2.2.3 on 2019-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190720_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uquestion',
            name='repeated',
            field=models.IntegerField(blank=True, null=True, verbose_name='repeated'),
        ),
    ]
