# Generated by Django 2.2.3 on 2019-08-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_personalizedquiz_tempory_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedquiz',
            name='session_closed',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='session_closed'),
        ),
    ]
