# Generated by Django 2.2.3 on 2019-08-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190805_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone1',
            field=models.ForeignKey(blank=True, default='America/St_Johns', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Timezone'),
        ),
    ]
