# Generated by Django 2.2.3 on 2019-07-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190722_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uquestion',
            name='repeated',
        ),
        migrations.AddField(
            model_name='uquestion',
            name='wrong_answer_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='wrong_answer_date'),
        ),
    ]
