# Generated by Django 2.2.3 on 2019-08-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_personalizedquiz_session_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedquiz',
            name='session_closed',
            field=models.CharField(blank=True, default='0', max_length=1024, null=True, verbose_name='session_closed'),
        ),
    ]
