# Generated by Django 2.2.3 on 2019-08-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190816_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedquiz',
            name='previous_question_list',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Previous Question List'),
        ),
    ]
