# Generated by Django 2.2.3 on 2019-07-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190722_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='uquestion',
            name='today_wrong_answer',
            field=models.IntegerField(blank=True, null=True, verbose_name='today_wrong_answer'),
        ),
    ]
