# Generated by Django 2.2.3 on 2019-08-16 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190816_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedquiz',
            name='session_closed',
            field=models.CharField(blank=True, default=datetime.datetime(2019, 8, 16, 8, 52, 1, 747373), max_length=1024, null=True, verbose_name='session_closed'),
        ),
    ]
