# Generated by Django 2.2.3 on 2019-08-16 10:00

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190816_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizedquiz',
            name='session_closed',
        ),
        migrations.AlterField(
            model_name='personalizedquiz',
            name='previous_question_list',
            field=models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Previous Question List'),
        ),
    ]
