# Generated by Django 2.2.3 on 2019-07-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_uquestion_today_wrong_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedquiz',
            name='rember',
            field=models.BooleanField(default=False, verbose_name='rember_me'),
        ),
    ]
