# Generated by Django 2.2.3 on 2019-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190816_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedquiz',
            name='session_time',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='session_time'),
        ),
        migrations.AlterField(
            model_name='personalizedquiz',
            name='previous_question_list',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Previous Question List'),
        ),
    ]
