# Generated by Django 2.2.3 on 2019-07-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_personalizedquiz_rember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedquiz',
            name='rember',
            field=models.CharField(blank=True, default=0, max_length=24, null=True, verbose_name='rember'),
        ),
    ]
