# Generated by Django 2.2.3 on 2019-07-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190729_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedquiz',
            name='total_new_question',
            field=models.CharField(blank=True, default=0, max_length=24, null=True, verbose_name='total_new_question'),
        ),
        migrations.AddField(
            model_name='personalizedquiz',
            name='total_repeat',
            field=models.CharField(blank=True, default=0, max_length=24, null=True, verbose_name='total_repeat'),
        ),
    ]
