# Generated by Django 2.2.3 on 2019-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_personalizedquiz_question_attemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedquiz',
            name='question_attemp',
            field=models.IntegerField(blank=True, default=0, max_length=24, null=True, verbose_name='question_attemp'),
        ),
    ]
