# Generated by Django 2.2.3 on 2019-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_personalizedquiz_question_repe'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedquiz',
            name='correction',
            field=models.IntegerField(blank=True, default=0, max_length=24, null=True, verbose_name='correction'),
        ),
    ]
